apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cool-catalog-gdlt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jinqi-1-tenant/cool-catalog/cool-catalog-gdlt@sha256:6475e48650014824d0c7fb4a3b4f62106e1450092349eb3b9415c9eec0479411
        name: container-image
        resources: {}
status: {}
