apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cool-catalog-gdlt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jinqi-1-tenant/cool-catalog/cool-catalog-gdlt@sha256:e7729757138d408527c9d223454436b3eb94821af409b46bd4f1555c6443486b
        name: container-image
        resources: {}
status: {}
