apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cool-catalog-gdlt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jinqi-1-tenant/cool-catalog/cool-catalog-gdlt@sha256:a96b1888224f43731df6bed081a77f577071e9aa2924155a9702c204a3cfbaa5
        name: container-image
        resources: {}
status: {}
