apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cool-catalog-gdlt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cool-catalog-gdlt
    app.kubernetes.io/part-of: cool-catalog
  name: cool-catalog-gdltt4ue
spec:
  port:
    targetPort: 8084
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cool-catalog-gdlt
    weight: 100
status: {}
