apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cool-catalog-gdlt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cool-catalog-gdlt
    app.kubernetes.io/part-of: cool-catalog
  name: cool-catalog-gdlt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cool-catalog-gdlt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cool-catalog-gdlt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jinqi-1-tenant/cool-catalog/cool-catalog-gdlt@sha256:e7729757138d408527c9d223454436b3eb94821af409b46bd4f1555c6443486b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8084
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
